import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TrendingCoinsContextProdiver from "@/context/TrendingCoinsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Koinx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TrendingCoinsContextProdiver>
        <body className={inter.className}>{children}</body>
      </TrendingCoinsContextProdiver>
    </html>
  );
}
